apiVersion: batch/v1
kind: Job
metadata:
  name: imagenet-train-job
spec:
  template:
    metadata:
      labels:
        app: imagenet-train-job
    spec:
      containers:
      - name: imagenet-trainer
        image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        volumeMounts:
          - name: imagenet-pvc
            mountPath: /mnt/imagenet
          - name: cav-pvc
            mountPath: /mnt/data
        workingDir: /mnt/data
        resources:
          limits:
            memory: 12Gi
            cpu: 4000m
            nvidia.com/gpu: 3
          requests:
            memory: 12Gi
            cpu: 4000m
            nvidia.com/gpu: 3
        env:
          - name: IMAGENET_PATH
            value: /mnt/imagenet
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install -r requirements.txt
            python train.py

      volumes:
        - name: imagenet-pvc
          persistentVolumeClaim:
            claimName: imagenet-pvc
        - name: cav-pvc
          persistentVolumeClaim:
            claimName: cav-pvc

      restartPolicy: Never