apiVersion: batch/v1
kind: Job
metadata:
  name: imagenet-train-job
spec:
  template:
    metadata:
      labels:
        app: imagenet-train-job
    spec:
      containers:
      - name: imagenet-trainer
        image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        volumeMounts:
          - name: imagenet-pvc
            mountPath: /mnt/imagenet
          - name: code-pvc
            mountPath: /workspace
        workingDir: /workspace
        resources:
          limits:
            memory: 12Gi
            cpu: 4000m
            nvidia.com/gpu: 3
          requests:
            memory: 12Gi
            cpu: 4000m
            nvidia.com/gpu: 3
          
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            git clone https://github.com/your-username/your-repo.git /workspace/your-repo
            cd /workspace/your-repo
            pip install -r requirements.txt
            python train.py

      volumes:
        - name: imagenet-pvc
          persistentVolumeClaim:
            claimName: imagenet-pvc
        - name: code-pvc
          persistentVolumeClaim:
            claimName: code-pvc

      restartPolicy: Never